# This is a basic workflow to help you get started with Actions

name: Flutter-Android-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Set Up Flutter
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    #Building android apk and appbundle
    - run: cd packages/math-u-similarity-index && flutter --version && cd ../..
    - run: cd packages/math-u-similarity-index && flutter pub get && cd ../..
    - run: cd packages/math-u-similarity-index && flutter test && cd ../..
    - run: cd packages/math-u-similarity-index && flutter build apk && cd ../..
    - run: cd packages/math-u-similarity-index && flutter build appbundle && cd ../..
